name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'yarn'

      - name: Run install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
      

      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install

      # - name: Lint
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: lint

      # - name: Typecheck
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: typecheck

      # - name: Test
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test

      # - uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build

      # Placeholder for Docker builds
      # - name: Build Docker Images
      #   run: |
      #     docker build -t api:latest -f apps/api/Dockerfile .
      #     docker build -t web:latest -f apps/web/Dockerfile .
